### ISSUE TITLE
Tech Debt: Get rid of execute_inline method

### ISSUE THREAD

**Issue by mdurban** [mdurban/rspec-shell-expectations#12]
The execute_inline method is useful for tests, but does not have any real world applicable cases. Remove this method and change tests to use the remaining, actually useful methods.

**Comment by mdurban** [comment]
I'm second guessing this now. Execute_inline, while useless when actually using the framework, makes tests much easier to write and examples of how to use the framework much easier to understand.

**Comment by bennyhat** [comment]
You're right. We can just leave it for now, as it helps people try it out more readily.
