### ISSUE TITLE
Tech Debt: Remove sub commands

### ISSUE THREAD

**Issue by mdurban** [mdurban/rspec-shell-expectations#14]
Sub commands obfuscate the flow of how this library works and results in a lot of duplicated code, but does not give us many benefits. Let's make it a 👻

**Comment by bennyhat** [comment]
Just a quick observation. The with_args method is really the only reason that the StubbedCall (sub-command) class exists. This is used for:

- sub-command creation
- output and exit code mocking

The first one can be addressed in several ways. The second one can be addressed by coming up with a more standard stubbing call, similar to how real rspec TestDoubles are mocked (Ex. allow(stubbed_command).to receive(:call).with('argument_one').and_return('output message')):

https://relishapp.com/rspec/rspec-mocks/v/3-1/docs/basics/allowing-messages

**Comment by mdurban** [comment]
Can we close this?

**Comment by bennyhat** [comment]
https://github.com/mdurban/rspec-shell-expectations/pull/17
