### ISSUE TITLE
Feature: partial mocks/stubs

### ISSUE THREAD

**Issue by bennyhat** [mdurban/rspec-shell-expectations#9]
Right now we can't stub or mock functions that are in the same shell script under test. This isn't a huge deal for library scripts, but may bite us when we are testing executed tests.

One idea is to inject overridden functions into a  shim script (/tmp/whatever/function-overrides.sh and then repoint, them like so:

```
function git {
  /tmp/whatever/git $@
}
readonly -f git
```

The only problem with this is that it spits out a readonly message to stderr when another file overrides it, so we may have to build something into the execute_script/function to grep that out of the output :/

**Comment by mdurban** [comment]
Close? 🚪

**Comment by bennyhat** [comment]
Added by https://github.com/mdurban/rspec-shell-expectations/pull/16
